run-ocropy: Die loudly for files not in current working directory

diff --git a/run-ocropy b/run-ocropy
--- a/run-ocropy
+++ b/run-ocropy
@@ -2,7 +2,6 @@
 
 typeset -A ALLOWED_COMMANDS
 
-
 ALLOWED_COMMANDS[dewarp]="dewarp lines as used for the recognizer"
 ALLOWED_COMMANDS[econf]="Compute the edit distances between ground truth and recognizer output"
 ALLOWED_COMMANDS[errs]="Compute the edit distances between ground truth and recognizer output"
@@ -18,7 +17,7 @@ ALLOWED_COMMANDS[rtrain]="train an RNN recognizer"
 ALLOWED_COMMANDS[visualize-results]="Generate HTML for debugging a book directory"
 
 DOCKER_IMAGE=${DOCKER_IMAGE:-kbai/ocropy}
-WORKING_DIR="$PWD"
+WORKING_DIR="$(realpath "$PWD")"
 
 help() {
     echo "$0 [--help] [--sudo] [--image <image-name>] [--working-dir <working-dir>] <cmd> [args...]"
@@ -69,4 +68,18 @@ elif [[ -z "${ALLOWED_COMMANDS[$CMD]}" ]];then
     help "Unknown command '$CMD'. Allowed: ${!ALLOWED_COMMANDS[*]}"
 fi
 
-$SUDO docker run --rm -v "$WORKING_DIR:/work" "$DOCKER_IMAGE" "ocropus-$CMD" "$@"
+declare -a ARGS=()
+for maybeFile in "$@";do
+    if [[ -e "$maybeFile" ]];then
+        fullpath=$(realpath "$maybeFile")
+        if [[ "$fullpath" != "$WORKING_DIR"* ]];then
+            echo -e "\x1b[31;1mERROR\x1b[0m File '$maybeFile' not in WORKING_DIR '$WORKING_DIR'"
+            exit 1
+        fi
+        ARGS+=("$(realpath --relative-to="$WORKING_DIR" "$maybeFile")")
+    else
+        ARGS+=("$maybeFile")
+    fi
+done
+
+$SUDO docker run --rm -v "$WORKING_DIR:/work" "$DOCKER_IMAGE" "ocropus-$CMD" "${ARGS[@]}"
